resilience4j:
  circuitbreaker:
    instances:
      backendService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 1000
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 500
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  ratelimiter:
    instances:
      backendService:
        limitForPeriod: 10
        limitRefreshPeriod: 1000
        timeoutDuration: 0