resilience4j:
  circuitbreaker:
    instances:
      UserService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 1000
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 500
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  ratelimiter:
    instances:
      UserService:
        limitForPeriod: 10
        limitRefreshPeriod: 1000
        timeoutDuration: 0
  retry:
    instances:
      UserService:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - java.io.IOException
  bulkhead:
    instances:
      UserService:
        maxConcurrentCalls: 5
        maxWaitDuration: 500